name: Release Charts

on:
  push:
    branches:
      - master
      - gh-pages

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
          with:
            charts_dir: charts
            owner: 4c74356b41
            git-base-url: https://api.github.com/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
